#!/bin/bash
set -u

# Directory where we will simulate the compromised environment
# We'll put it in the current user's home directory under 'test_compromise_env'
TARGET_DIR="${HOME}/test_compromise_env"

echo "Preparing compromised environment in: $TARGET_DIR"

# 1. Create the target directory structure
mkdir -p "$TARGET_DIR/node_modules/02-echo"

# 2. Create a package.json for the compromised package '02-echo'
# The scanner checks for "name" and "version" in package.json files.
cat > "$TARGET_DIR/node_modules/02-echo/package.json" <<EOF
{
  "name": "02-echo",
  "version": "0.0.7",
  "description": "Simulated compromised package for testing"
}
EOF
echo "Created compromised package.json: $TARGET_DIR/node_modules/02-echo/package.json"

# 3. Create a package-lock.json with the compromised version
# The scanner greps for "name": "..." and "version": "..." in package-lock.json
cat > "$TARGET_DIR/package-lock.json" <<EOF
{
  "name": "test-project",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "test-project",
      "version": "1.0.0",
      "dependencies": {
        "02-echo": "^0.0.7"
      }
    },
    "node_modules/02-echo": {
      "version": "0.0.7",
      "resolved": "https://registry.npmjs.org/02-echo/-/02-echo-0.0.7.tgz",
      "integrity": "sha512-simulated-hash"
    }
  },
  "dependencies": {
    "02-echo": {
      "version": "0.0.7",
      "resolved": "https://registry.npmjs.org/02-echo/-/02-echo-0.0.7.tgz",
      "integrity": "sha512-simulated-hash"
    }
  }
}
EOF
echo "Created compromised package-lock.json: $TARGET_DIR/package-lock.json"

# 4. Create a yarn.lock with the compromised version
# The scanner looks for "pkg@version" in yarn.lock
cat > "$TARGET_DIR/yarn.lock" <<EOF
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


02-echo@0.0.7:
  version "0.0.7"
  resolved "https://registry.npmjs.org/02-echo/-/02-echo-0.0.7.tgz#hash"
  integrity sha512-simulated-hash==

EOF
echo "Created compromised yarn.lock: $TARGET_DIR/yarn.lock"

echo "---------------------------------------------------"
echo "Setup complete."
echo "You can now run the scanner to verify detection."
echo "Example command:"
echo "  sudo ./check_compromised_npm_v3.sh"
echo "---------------------------------------------------"
